### ISSUE TITLE
JavaScript error when viewing Table for multiple games

### ISSUE THREAD

**Issue by LucasPickering** [SaltieRL/DistributedReplays#230]
Go to [this link](https://calculated.gg/details?ids=A36ED15411E91C349584A59B2C9F5CBB&ids=A3D078F611E91C333EF3A59B7C977244&ids=93A21FDA11E91C323CDBA59B1737A86E&ids=B0E685E611E91C3123BA5DA389425810&ids=BB58251A11E91C2D58BE5DA3198661CE&ids=CF63C89411E91C2C1AFC5DA3D6D201EF&ids=ECF5D72211E91C2B4A765DA31E040DB9&ids=C443301411E91C2A9DA05DA342D9ABA0), then click the Table tab. The page goes blank and this error appears in the console:

```
TypeError: "e.stats.find(...) is undefined"
	sortPlayerStats https://calculated.gg/static/js/main.e0b65916.js:1:1866519
	sortPlayerStats https://calculated.gg/static/js/main.e0b65916.js:1:1866491
	render https://calculated.gg/static/js/main.e0b65916.js:1:1867626
	Ki https://calculated.gg/static/js/main.e0b65916.js:1:548082
	i https://calculated.gg/static/js/main.e0b65916.js:1:547925
	ta https://calculated.gg/static/js/main.e0b65916.js:1:550559
	ka https://calculated.gg/static/js/main.e0b65916.js:1:564622
	Aa https://calculated.gg/static/js/main.e0b65916.js:1:564968
	fo https://calculated.gg/static/js/main.e0b65916.js:1:569640
	co https://calculated.gg/static/js/main.e0b65916.js:1:569294
	ja https://calculated.gg/static/js/main.e0b65916.js:1:567806
	enqueueSetState https://calculated.gg/static/js/main.e0b65916.js:1:536637
	setState https://calculated.gg/static/js/main.e0b65916.js:1:429123
	attemptToLoad https://calculated.gg/static/js/main.e0b65916.js:1:16793
 react-dom.production.min.js:169:139
```

**Comment by axelalex2** [comment]
This link is not working anymore, and even if fixed from /details to /replays/group it cannot load the mentioned replays anymore. Apart from that, i fixed that error in the table at some time ago when working on replay groups, since it appeared in every one of them. Here is the change: https://github.com/SaltieRL/DistributedReplays/commit/1d16ad22e986de4796538907a5ead4babc8851fe#diff-099cec046f31192b4651370f4c4a9c04
