### ISSUE TITLE
Clarification on stats

### ISSUE THREAD

**Issue by kurisu-gh** [SaltieRL/DistributedReplays#368]
Recently, I've been cleaning up the stats explanation page and I'd like to have some clarification on the following:

* `first_frame_in_game`: Seems to be a fixed point number.
* `is keyboard`: I thought it was a Boolean value but seems to be some sort of integer.
* `time_between_players`: Is this the time a player is not positioned first-man-up or last-man-back on the pitch? I guess it would be `time_in_game` - (`time_most_back_player` + `time_most_forward_player`)?
* `time_high_in_air`:  Amount of time a player is positioned at least goal height or above in the air?
* `time_in_corner`: Amount of time a player is positioned in corner sections of the map? What is really the "corner" here?
* `time_in_game`:  Seems to be number of seconds in game which should generally be 300 (60 sec x 5 min) ?
* `time_near_wall`: Amount of time the player is positioned near the wall? What does near the wall mean?
* `total_dribble_conts`: Should be "counts" I suppose. There is some explanation that says "second, third, ..." touch of a dribble? How exactly is it calculated? Is one dribble a series of touches that are within some time frame (say quarter of a second)?

## Speed discussion
* `time at boost speed`: Currently it is "Total time at a speed only reachable by using boost (or flips)."
* `time at super sonic`: Currently it is "Total time at max car speed. Trail is showing."
* `time at slow speed`: Total time at half the car speed reachable by just driving.

Super sonic is actually not max speed. Super sonic is 2200 uu/s whereas max speed is 2300 uu/s. Super sonic can be obtained via boosting or flipping. Max speed can be obtained by tapping boost once after achieving supersonic (and is maintained as long as you're driving in a straight line). See reference [video on max speed](https://www.youtube.com/watch?v=mlWY6x8g5Ps).

So I'm not sure if Calculated.gg considers this properly or not. Regardless, the current definitions of `time at boost speed` and `time at super sonic` seem strange and it would be great to get some clarification on that.

Once the stats are clarified, I'd be happy to update the stats explanations page and do a pull request.

**Comment by dtracers** [comment]
Responding inline 
> first_frame_in_game: Seems to be a fixed point number.
Yes this is the first frame that the player is completely loaded into the game and is able to interact with physics.  This is basically a useless stat but it could be used to detect lag in ranked games.  In unranked it is used for deciding how to calculate other stats since players can join midgame
> is keyboard: I thought it was a Boolean value but seems to be some sort of integer.
It is a value of confidence in how sure are we that the player is using a keyboard.   Also this value is very wonky in aggregation since you are aggregating a psuedo Boolean value.
> time_between_players: Is this the time a player is not positioned first-man-up or last-man-back on the pitch? I guess it would be time_in_game - (time_most_back_player + time_most_forward_player)?
Yes that is completely correct
> time_high_in_air: Amount of time a player is positioned at least goal height or above in the air?
Yes.  It is actually above the max height you can get from double jumping.
Or basically you need to use boost to reach this height
> time_in_corner: Amount of time a player is positioned in corner sections of the map? What is really the "corner" here?
I think this would probably need a picture.  For a lot of these time_location we might want to consider making images. If you come up with a way to display them or good backgrounds I can give you the exact coordinate values so we can plot them on images
> time_in_game: Seems to be number of seconds in game which should generally be 300 (60 sec x 5 min) ?
Yes it can be different for unranked entering late or leaving early or  overtime
> time_near_wall: Amount of time the player is positioned near the wall? What does near the wall mean?
Once again I think an image will be a good explanation. 
> total_dribble_conts: Should be "counts" I suppose. There is some explanation that says "second, third, ..." touch of a dribble? How exactly is it calculated? Is one dribble a series of touches that are within some time frame (say quarter of a second)?
This is total_dribble_continues.
It is essentially consecutive touches.  If you touch the ball twice in a row it is another dribble continue. 
> Speed discussion
> time at boost speed: Currently it is "Total time at a speed only reachable by using boost (or flips)."
> time at super sonic: Currently it is "Total time at max car speed. Trail is showing."
> time at slow speed: Total time at half the car speed reachable by just driving.
> Super sonic is actually not max speed. Super sonic is 2200 uu/s whereas max speed is 2300 uu/s. Super sonic can be obtained via boosting or flipping. Max speed can be obtained by tapping boost once after achieving supersonic (and is maintained as long as you're driving in a straight line). See reference video on max speed.

Yes we say super Sonic but actually use max speed.
I guess we could separate it into demo speed and Max speed.

We use 2300 for that stat as it is the most useful.
> 
> So I'm not sure if Calculated.gg considers this properly or not. Regardless, the current definitions of time at boost speed and time at super sonic seem strange and it would be great to get some clarification on that.

Yes so boost speed can be reached with just flips.  I guess you could call it any speed faster than what can be obtained by just pure throttle.

I hope these clarifications help

**Comment by kurisu-gh** [comment]
Very helpful! Thank you. I'll give some thought regarding the stats that could use a visual aid.

One more clarification:
`rank` vs `mmr`? mmr seems straight forward but what exactly is rank?

**Comment by dtracers** [comment]
Rank is the bucket you fit into.

Think Diamond 1, Diamond 2
I think there are 20 or so of them?

**Comment by kurisu-gh** [comment]
I see! Yes, there are 20 buckets from unranked to GC. The problem is that the number is fixed point so I'm not sure how the ranks correspond.

I checked the "rank" of Kronovi and Kuxir97, both GC in standard and when you run a side-by-side comparison, Kronovi's "rank" is 17.72 and Kuxir's is 18.34. 

Is it perhaps an average? I only think this because I figured both players should be at 20 currently, but if there are replays with the player not yet ranked (i.e. start of competitive season), then a few 1's were probably averaged in.

**Comment by Sciguymjm** [comment]
It's average of all games in all playlists. So yeah, they may be not GC in 1s.

**Comment by kurisu-gh** [comment]
Got it. I actually meant 1's as in the value of '1' added to the average in the case of placement matches, etc. Are the values I'm assuming correct? 20=GC and 1=unranked?

For center of mass calculations for team positioning, is the center mass including all players on the pitch? or is it based on just the center of mass of the player's team?

**Comment by dtracers** [comment]
Center of mass is per a team.
