### ISSUE TITLE
Logo Antialiasing

### ISSUE THREAD

**Issue by dbauducco** [SaltieRL/DistributedReplays#51]
Antialiasing of the logo in the top left makes it look blurry

**Comment by kcolton** [comment]
This is a bit of a tricky one to get right for logotype unless you know the exact dimensions for each usage up front.

tl;dr: Since there is no type hinting made available through an image, the asset would need to be exported in to a size that is _pixel perfect_ at the usage resolution (2x if not an svg for hdpi). 

Sketch and photoshop have helpful tools for getting this right, but it presupposed you know the usage resolution exactly. If you are doing any % based resizing of logo, then you are pretty much SOL.*

*there could be some SVG hacks, but doubt it would be worth the effort.

**Comment by dbauducco** [comment]
Let TwoBack know. I made these issues for him.
